# Generated by Django 6.1.1 on 2026-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileindex',
            old_name='path',
            new_name='current_path',
        ),
        migrations.RemoveField(
            model_name='fileindex',
            name='size',
        ),
        migrations.AddField(
            model_name='fileindex',
            name='original_path',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
